version: "3.8"
networks:
    redis-network:
services:
    redis:
        image: redis
        container_name: atomicradio-api-cache
        expose:
          - 6379
        networks:
          - redis-network
    atomicradio-api:
        build: atomicradio-api:latest
        container_name: atomicradio-api
        volumes:
            - ./assets:/opt/src/assets
        ports:
            - "3010:3010"
            - "3011:3011"
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis
        networks:
            - redis-network
